# Pre-install of serice account, It is written as a pre-install hook. 
# A pre-install hook is run before the rest of the chart is loaded.

apiVersion: v1 
kind: Namespace 
metadata: 
  name: twistlock 

