stages:
  - build
  - twistlock
  - test
  - deploy

job 1:
  stage: build
  script:
  - docker version
  - docker info
  - docker build -t securethecloud/my_tweet_app:latest .

job 2:
  stage: twistlock
  script:
   - curl -k -u $username:$password --output ./twistcli $address/api/v1/util/twistcli
   - chmod +x ./twistcli
   - ./twistcli --version
   - IMAGEID=`docker images securethecloud/my_tweet_app:latest --format "{{.ID}}"`
   - ./twistcli images scan --details --address $address -u $username -p $password --compliance-threshold $compthreshold --vulnerability-threshold $vulnthreshold --grace-period $graceperiod --only-fixed $IMAGEID

job 3:
  stage: deploy
  script:
  - docker login -u $user_dockerhub -p $password_dockerhub
  - docker push securethecloud/my_tweet_app:latest
