kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: twistlock-console
  volume.beta.kubernetes.io/storage-class: standard

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.console.persistentVolumeSize }} 
  
