apiVersion: v1
kind: ReplicationController
metadata:
  name: twistlock-console
spec:
  replicas: 1
  selector:
    name: twistlock-console
  template:
    metadata:
      name: twistlock-console
      labels:
        name: twistlock-console
    spec:
      
      restartPolicy: Always
      serviceAccountName: twistlock-console
      containers:
      - name: twistlock-console
        image: "{{ .Values.global.imageName }}"
        ports:
        - name: mgmt-https
          containerPort: {{ .Values.console.httpsPort }} 
        - name: communication
          containerPort: {{ .Values.console.commPort }} 
        - name: mgmt-http
          containerPort: {{ .Values.console.httpPort }}  
        env:
        - name: SERVICE
          value: "<no value>"
        - name: CONSOLE_CN
          value: ""
        - name: CONSOLE_SAN
          value: "<no value>"
        - name: HIGH_AVAILABILITY_ENABLED
          value: "false"
        - name: KUBERNETES_ENABLED
          value: "<no value>"
        - name: CONFIG_PATH
          value: /data/config/twistlock.cfg
        - name: LOG_PROD
          value: "true"
        - name: DATA_RECOVERY_ENABLED
          value: "true"
        - name: COMMUNICATION_PORT
          value: "{{ .Values.console.commPort }}" 
        - name: MANAGEMENT_PORT_HTTPS
          value: "{{ .Values.console.httpsPort }}"
        - name: MANAGEMENT_PORT_HTTP
          value: "{{ .Values.console.httpPort }}" 
        - name: SCAP_ENABLED
          value: ""
        
        securityContext:
          readOnlyRootFilesystem: true
          
        volumeMounts:
        - name: twistlock-config-volume
          mountPath: "/data/config/"
        - name: console-persistent-volume
          mountPath: "/var/lib/twistlock"
          subPath: "var/lib/twistlock"
        
        - name: console-persistent-volume
          mountPath: "/var/lib/twistlock-backup"
          subPath: "var/lib/twistlock-backup"
        
        - name: syslog-socket
          mountPath: "/dev/log"
      
      volumes:
      - name: console-persistent-volume
        
        persistentVolumeClaim:
          claimName: twistlock-console
      - name: syslog-socket
        hostPath:
          path: "/dev/log"
      - name: twistlock-config-volume
        configMap:
          name: twistlock-console
      
