apiVersion: v1
kind: Service
metadata:
  name: twistlock-console 
  namespace: twistlock
  labels:
    app: twistlock-console

spec:
  ports:
  - name: communication-port
    port: {{ .Values.console.commPort }}   

  - name: management-port-https
    port: {{ .Values.console.httpsPort }} 
  
  - name: mgmt-http
    port: {{ .Values.console.httpPort }} 

  selector:
    name: twistlock-console

  type: {{ .Values.console.serviceType }} 



