apiVersion: v1
kind: Service
metadata:
  name: twistlock-console
  namespace: twistlock
  labels:
    app: twistlock-console

spec:
  ports:
  - name: communication-port
    port: {{ .Values.commPort }}

  - name: management-port-https
    port: {{ .Values.httpsPort }}

  - name: mgmt-http
    port: {{ .Values.httpPort }}

  selector:
    name: twistlock-console

  type: {{ .Values.serviceType }}



